### PR TITLE
JBLOGGING-113 Making all package imports optional in OSGi manifest

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by jamezp** [comment]
I tried to look at the [plugin documentation](http://svn.apache.org/repos/asf/felix/releases/maven-bundle-plugin-2.3.7/doc/site/manifest-mojo.html#instructions) and it was pretty worthless in describing what the `instructions` configuration option does. I assume the wildcard just takes the dependencies from the pom and adds the appropriate package name. Is that correct?

**Comment by gunnarmorling** [comment]
The `instructions` element accepts options as understood by the [BND tool](http://www.aqute.biz/Bnd/Bnd).

For the `Import-Package` rule the created class files are analyzed and the actually referenced Java packages are collected. So the wild card references all packages used in the project, it's not based on Maven dependencies.

**Comment by jamezp** [comment]
Excellent, that's what I was looking for thanks!

**Comment by gunnarmorling** [comment]
Cool :)

**Pull request merged**
