### PR TITLE
[3.4][JBLOGGING-165][JBLOGGING-167] Upgrade slf4j 2.0.5 and logback 1.3.5

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes:
* https://issues.redhat.com/browse/JBLOGGING-165
* https://issues.redhat.com/browse/JBLOGGING-167

Upstream https://github.com/jboss-logging/jboss-logging/pull/53

### CODE REVIEW

**Comment by boris-unckel** [comment]
@jamezp The 3.4 branch PR for it - could you review and approve, please?

**Comment by jamezp** [comment]
I'm not sure this should go into the 3.4 branch. It's debatable it should go into the 3.5 IMO as well because it's a major component upgrade.

**Comment by boris-unckel** [comment]
The difference between the 3.5PR https://github.com/jboss-logging/jboss-logging/pull/53 and this one is the logback version, which requires Java 8 here and in 3.5 Java 11. The interface from a jboss-logging point of view does not change, it works fine for both.

**Comment by jamezp** [comment]
For now I think we'll close this as the 3.4 branch has nothing of note in it.

**Pull request closed without merging**
